path_annotations: <YOUR_ANNOTATIONS_PATH>/saco_frames_test_sets/annotations/

# Paths with downloaded data
droid_path: <YOUR_DATASET_PATH>/saco_frames_test_sets/droid/
sav_path: <YOUR_DATASET_PATH>/saco_frames_test_sets/sav/
ego4d_path: <YOUR_DATASET_PATH>/saco_frames_test_sets/ego4d/
yt1b_path: <YOUR_DATASET_PATH>/saco_frames_test_sets/yt1b/

# Configuration to download and extract video frames
cookies_path: <YOUR_COOKIES_PATH>/cookies.txt  # Required to download YT1B videos
update_annotation_yt1b: true
update_annotation_ego4d: true

sav_videos_fps_6_download_path: ''

remove_downloaded_videos_yt1b: false
remove_downloaded_videos_droid: false
remove_downloaded_videos_ego4d: false
remove_downloaded_videos_sav: false

# Configuration for visualization of data
num_images_show: 5
saco_subset_show: yt1b  # Options: [yt1b, ego4d, sav, droid]
directory_save: <YOUR_SAVE_DIR>
